### ISSUE TITLE
The upgrade doesn't work

### ISSUE THREAD

**Issue by devkzer** [tygalive/Woo-Custom-Gateway#1]
The upgrade doesn't work for my Woo Custom Gateway, when I put the order doesn't show me What I write in "Thank you Instructions" the Instructions that will be shown on the thank you page, just i see Thank you

**Comment by devkzer** [comment]
I'm talking about the Version: 1.5.1

**Comment by devkzer** [comment]
<img width="1135" alt="Screenshot 2023-02-27 at 00 23 29" src="https://user-images.githubusercontent.com/126425658/221443802-2feb0f7a-fabe-45ed-8d47-c344e92b1e5d.png">
<img width="495" alt="Screenshot 2023-02-27 at 00 24 20" src="https://user-images.githubusercontent.com/126425658/221443804-9801b427-5e9e-44ad-a0f9-02c20fd17c12.png">
<img width="700" alt="Screenshot 2023-02-27 at 00 24 40" src="https://user-images.githubusercontent.com/126425658/221443806-ecdf5d0f-8161-4f01-bb37-0cf019f91440.png">

**Comment by richard-muvirimi** [comment]
Thank you this has since been resolved in 1.5.3
